#!/usr/bin/env python3
"""Assemble the standard CS surgery object from existing T73 programs.

This computes a replayable model of Sigma_A^0:

- T^3 = R^3/Z^3 with linear monodromy A
- mapping torus T^3 x I / (x,0)~(A x, 1)
- section circle {0} x S^1 (the unique fixed point of A, since det(A-I)=1)
- product framing epsilon=0
- 0-surgery: remove a neighbourhood of the section, glue D^2 x S^2
- PL polylines in the universal cover for the three straight mapping-torus
  cores, generated by the compact Kirby crossing rule

It then binds the Johnson replacement, X_J, and the E13 close certificate.
The close certificate supplies the PL psi 3-cells, railroad attaching link,
reduced PD, and staged Kirby pipeline.  Lean ExternalGeometry /
CSExternalGeometry / CSTopologyData remain uninhabited.  No counterexample
is claimed.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from fractions import Fraction
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
P0 = ROOT / "audit" / "t73_p0_johnson_certificate.json"
C = ROOT / "audit" / "t73_c_comparison_witness.json"
S = ROOT / "audit" / "t73_s_relative_moves_certificate.json"
P3 = ROOT / "audit" / "t73_p3_four_handle.json"
OUTPUT = ROOT / "audit" / "t73_e13_identification.json"
LEAN_FINITE = ROOT / "Smooth4PC" / "T73Finite.lean"

MATRIX_A = (
    (0, 269, 1240),
    (0, 41, 189),
    (1, 0, 32),
)
C_AR = (
    (0, 0, 1),
    (713, 83, 0),
    (-902, -105, -10),
)
R = (
    (71, -466, 1),
    (-610, 4004, -7),
    (1, -7, -2),
)
AXES = ("x", "y", "z")


def load(name: str):
    path = ROOT / "scripts" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def canonical_sha(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest().upper()


def det3(matrix: tuple[tuple[int, ...], ...]) -> int:
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]
    return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)


def matmul(
    left: tuple[tuple[int, ...], ...], right: tuple[tuple[int, ...], ...]
) -> tuple[tuple[int, ...], ...]:
    return tuple(
        tuple(sum(left[i][k] * right[k][j] for k in range(3)) for j in range(3))
        for i in range(3)
    )


def minus_i(matrix: tuple[tuple[int, ...], ...]) -> tuple[tuple[int, ...], ...]:
    return tuple(
        tuple(matrix[i][j] - (1 if i == j else 0) for j in range(3)) for i in range(3)
    )


def encode_point(point: tuple[Fraction, Fraction, Fraction]) -> list[str]:
    return [str(value) for value in point]


def cover_core(column: int) -> dict[str, Any]:
    """Straight-line image of the j-th coordinate spine under A, in R^3."""
    compact = load("generate_t73_compact_kirby_ledger")
    vector = tuple(MATRIX_A[row][column] for row in range(3))
    tie_order = tuple((column - offset) % 3 for offset in range(3))
    rank = {axis: index for index, axis in enumerate(tie_order)}
    events: list[tuple[Fraction, int, int]] = []
    for axis, amount in enumerate(vector):
        if amount < 0:
            raise AssertionError("CS cover cores require nonnegative A columns")
        if amount == 0:
            continue
        for level in range(1, amount + 1):
            events.append((Fraction(level, amount), rank[axis], axis))
    events.sort()
    letters = [AXES[axis] for _, _, axis in events]
    if letters != compact.linear_crossing_word(column):
        raise AssertionError(f"cover polyline word disagrees with compact column {column}")
    points = [(Fraction(0), Fraction(0), Fraction(0))]
    for time, _, _ in events:
        points.append(tuple(time * vector[i] for i in range(3)))  # type: ignore[arg-type]
    endpoint = tuple(Fraction(value) for value in vector)
    if points[-1] != endpoint:
        points.append(endpoint)
    if points[0] != (Fraction(0), Fraction(0), Fraction(0)):
        raise AssertionError("cover core does not start at the origin")
    if points[-1] != endpoint:
        raise AssertionError("cover core does not end at A e_j")
    encoded = [encode_point(point) for point in points]
    return {
        "column": column,
        "name": f"m_{column + 1}",
        "vector": list(vector),
        "event_count": len(letters),
        "vertex_count": len(encoded),
        "start": encode_point(points[0]),
        "end": encode_point(points[-1]),
        "word": letters,
        "word_sha256": compact.word_record(letters)["sha256"],
        "polyline_sha256": canonical_sha(encoded),
        "prefix": encoded[:4],
        "suffix": encoded[-4:],
        "ambient": "universal cover R^3 of T^3=R^3/Z^3",
        "rule": (
            "straight segment from 0 to A e_j; vertices at the compact Kirby "
            "rational crossing times"
        ),
    }


def mapping_torus_core(column: int, fiber: dict[str, Any]) -> dict[str, Any]:
    """Combinatorial mapping-torus loop of the compact word t * image * T * e_j^{-1}."""
    compact = load("generate_t73_compact_kirby_ledger")
    word = compact.mapping_torus_word(column)
    return {
        "name": f"m_{column + 1}",
        "word": compact.word_record(word),
        "cover_fiber_leg": fiber,
        "base_1_handle_legs": ["t", "T"],
        "bottom_spine": {
            "from": encode_point((Fraction(0), Fraction(0), Fraction(0))),
            "to": encode_point(
                tuple(Fraction(1 if i == column else 0) for i in range(3))
            ),
            "letter": AXES[column],
        },
        "quotient_rule": "(x,0)~(A x,1) identifies (A e_j,1) with (e_j,0)",
    }


def require_lean_matrix() -> None:
    text = LEAN_FINITE.read_text(encoding="utf-8")
    for needle in (
        "| 0, 0 => 0",
        "| 0, 1 => 269",
        "| 0, 2 => 1240",
        "| 1, 0 => 0",
        "| 1, 1 => 41",
        "| 1, 2 => 189",
        "| 2, 0 => 1",
        "| 2, 1 => 0",
        "| 2, 2 => 32",
        "theorem detA_eq_one",
        "theorem detAMinusI_eq_one",
    ):
        if needle not in text:
            raise AssertionError(f"T73Finite.lean is missing {needle!r}")


def generate() -> dict[str, Any]:
    compact = load("generate_t73_compact_kirby_ledger")
    factor = load("factor_t73_matrix_johnson").generate()
    ledger = compact.generate_ledger()
    p0 = json.loads(P0.read_text(encoding="utf-8"))
    c = json.loads(C.read_text(encoding="utf-8"))
    s = json.loads(S.read_text(encoding="utf-8"))
    p3 = json.loads(P3.read_text(encoding="utf-8"))

    if factor["matrix_product_status"] != "PASS" or factor["matrix_A"] != [list(row) for row in MATRIX_A]:
        raise AssertionError("Johnson transvections do not reconstruct A")
    if p0["verdict"] != "PASS" or not p0["checks"]["exact_compact_m2"]:
        raise AssertionError("E13 refuses to bind an unmatched Johnson m2 word")
    if p0["checks"]["matrix_factorization"] is not True:
        raise AssertionError("E13 requires the Johnson factorization of A")
    if p0["checks"]["relative_fixed_ball"] is not True:
        raise AssertionError("E13 requires the Johnson representative identity near 0")
    if p3["verdict"] != "PASS":
        raise AssertionError("E13 requires the X_J four-handle certificate")
    if p3["closed_manifold"]["identified_with_Sigma_A_0"]:
        raise AssertionError("P3 already claims an identification this object does not supply")
    if c["p0_witness_sha256"] != p0["certificate_sha256"]:
        raise AssertionError("C is not bound to P0")
    if s["dependencies"]["p0_certificate_sha256"] != p0["certificate_sha256"]:
        raise AssertionError("S is not bound to P0")
    if p3["p0_certificate_sha256"] != p0["certificate_sha256"]:
        raise AssertionError("P3 is not bound to P0")

    det_a = det3(MATRIX_A)
    det_a_minus_i = det3(minus_i(MATRIX_A))
    if det_a != 1 or det_a_minus_i != 1:
        raise AssertionError("CS matrix determinants are not both 1")
    if det3(R) != 1:
        raise AssertionError("AR conjugacy R is not unimodular")
    if matmul(C_AR, R) != matmul(R, MATRIX_A):
        raise AssertionError("C_AR R != R A")
    if det3(C_AR) != 1 or det3(minus_i(C_AR)) != 1:
        raise AssertionError("C_AR is not a determinant-one CS matrix")
    require_lean_matrix()

    cores = [cover_core(column) for column in range(3)]
    torus_loops = [mapping_torus_core(column, cores[column]) for column in range(3)]
    if cores[0]["vector"] != [0, 0, 1]:
        raise AssertionError("A e_1 is not e_3, so the (x,m_1) cancellation is not the AR pair")
    if ledger["cancellations"][0]["relative_twist"] != 0:
        raise AssertionError("base CS surgery is not recorded as epsilon=0")
    if ledger["cancellations"][1]["relative_twist"] != 0:
        raise AssertionError("(x,m_1) cancellation is not product-framed")
    if ledger["surviving_components"]["m_2"]["length"] != 311:
        raise AssertionError("compact reduced m2 length is not 311")

    present = {
        "linear_monodromy_is_A": True,
        "johnson_transvections_reconstruct_A": True,
        "det_A_eq_1": True,
        "det_A_minus_I_eq_1": True,
        "A_minus_I_invertible_over_Z": True,
        "unique_linear_fixed_point_is_origin": True,
        "section_circle_at_origin_epsilon_0": True,
        "cover_cores_match_compact_crossing_words": True,
        "ar_conjugacy_C_AR_R_eq_R_A": True,
        "johnson_m2_word_equals_compact_cs_m2": True,
        "johnson_forty_four_y_channels": bool(p0["checks"]["forty_four_channels"]),
        "johnson_relative_identity_near_origin": bool(p0["checks"]["relative_fixed_ball"]),
        "two_product_cancellations_epsilon_0": True,
        "x_j_four_handle_picture_bound": True,
        "iwaki_2_1_applies_to_this_cs_object": True,
    }
    close = load("certify_t73_e13_close").generate()
    close.pop("_pd", None)
    if close["verdict"] != "IDENTIFIED_CS_HANDLE_PICTURE":
        raise AssertionError("E13 close did not identify the CS handle picture")
    if not close["checks"]["identified_with_Sigma_A_0"]:
        raise AssertionError("E13 close did not set identified_with_Sigma_A_0")
    if close["p0_certificate_sha256"] != p0["certificate_sha256"]:
        raise AssertionError("E13 close is not bound to P0")
    if close["p3_certificate_sha256"] != p3["certificate_sha256"]:
        raise AssertionError("E13 close is not bound to P3")
    missing_maps = [
        item for item in close["resolved_maps"] if item["status"] == "OPEN"
    ]
    if [item["id"] for item in missing_maps] != ["lean_cs_topology_data"]:
        raise AssertionError("E13 close left a geometric map open")

    cs_object = {
        "name": "Sigma_A^0",
        "construction": "Cappell-Shaneson 0-surgery on the mapping torus of A",
        "fiber": {
            "manifold": "T^3=R^3/Z^3",
            "origin": ["0", "0", "0"],
            "ar_scaled_model": (
                "scripts/build_t73_ar_torus.py uses period 4 and Q=(-1,-1,-1); "
                "that Q is not a fixed point of linear A. The CS section used here "
                "is the origin, which is the unique fixed point."
            ),
        },
        "monodromy": {
            "matrix_A": [list(row) for row in MATRIX_A],
            "action": "phi_A(x)=A x mod Z^3",
            "johnson_transvection_count": factor["unit_alpha_move_count"],
            "johnson_factorization_sha256": factor["witness_sha256"],
        },
        "mapping_torus": {
            "model": "T^3 x [0,1] / (x,0)~(A x, 1)",
            "triangulated_4_complex": False,
            "section_circle": {
                "point": ["0", "0", "0"],
                "parametrization": "{0} x S^1",
                "fixed_by_linear_A": True,
                "framing": "untwisted product framing epsilon=0",
            },
        },
        "surgery": {
            "kind": "0-framed surgery on the section circle",
            "remove": "neighbourhood S^1 x D^3 of the section",
            "glue": "D^2 x S^2",
            "handle": "h_CS",
            "cancels": "mapping-torus 1-handle t",
            "relative_twist": 0,
        },
        "cover_cores": cores,
        "mapping_torus_loops": [
            {
                "name": loop["name"],
                "word_sha256": loop["word"]["sha256"],
                "word_length": loop["word"]["length"],
                "cover_polyline_sha256": loop["cover_fiber_leg"]["polyline_sha256"],
                "quotient_rule": loop["quotient_rule"],
            }
            for loop in torus_loops
        ],
        "ar_conjugacy": {
            "C_AR": [list(row) for row in C_AR],
            "R": [list(row) for row in R],
            "identity": "C_AR * R = R * A",
            "det_R": 1,
            "det_C_AR": 1,
            "det_C_AR_minus_I": 1,
        },
        "cancellations": ledger["cancellations"],
        "surviving_2_handles": {
            "labels": ledger["marking_policy"]["component_labels"],
            "handle_counts_after_two_cancellations": {
                "h0": 1,
                "h1": 2,
                "h2": 5,
                "h3": 3,
                "h4": 1,
            },
            "m2_length": ledger["surviving_components"]["m_2"]["length"],
            "m3_length": ledger["surviving_components"]["m_3"]["length"],
            "compact_ledger_sha256": ledger["ledger_sha256"],
        },
        "iwaki_source": (
            "Iwaki 2024 Proposition 2.1: det(A-I)=+-1 iff this construction "
            "is a homotopy 4-sphere"
        ),
        "homotopy_sphere_by_iwaki": True,
        "identified_with_X_J": True,
    }

    result: dict[str, Any] = {
        "schema": "t73_e13_identification/v2",
        "p0_certificate_sha256": p0["certificate_sha256"],
        "c_witness_sha256": c["witness_sha256"],
        "s_relative_sha256": s["certificate_sha256"],
        "p3_certificate_sha256": p3["certificate_sha256"],
        "e13_close_sha256": close["certificate_sha256"],
        "standard_cs_object": cs_object,
        "x_j": {
            "name": p3["closed_manifold"]["name"],
            "construction": close["closed_manifold"]["construction"],
            "identified_with_Sigma_A_0": True,
            "s_one_handle_count": 3,
            "cs_remaining_one_handle_count": 2,
            "p0_strands_are_selected_y_channels_of_railroad_link": True,
            "p3_certificate_claims_identification": False,
        },
        "present_maps": present,
        "resolved_maps": close["resolved_maps"],
        "missing_maps": missing_maps,
        "checks": {
            "cs_object_computed": True,
            "identified_with_Sigma_A_0": True,
            "all_present_maps": all(present.values()),
            "missing_map_count": len(missing_maps),
            "counterexample_not_claimed": True,
            "uniqueness_of_regular_neighborhoods_used": False,
            "isotopy_extension_used_to_identify_x_j": False,
            "lean_cs_topology_data_inhabited": False,
        },
        "E13_status": "PASS",
        "verdict": "IDENTIFIED_CS_HANDLE_PICTURE",
        "scope": (
            "Standard Cappell-Shaneson surgery object Sigma_A^0 together with "
            "the constructed Johnson CS handle picture of X_J.  Iwaki 2.1 "
            "applies to this identified pair.  Lean CSTopologyData remains "
            "uninhabited, and no counterexample is claimed."
        ),
    }
    result["certificate_sha256"] = canonical_sha(
        {key: value for key, value in result.items() if key != "certificate_sha256"}
    )
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.write:
        OUTPUT.write_text(
            json.dumps(generated, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        print(f"WROTE={OUTPUT}")
    if args.check:
        committed = json.loads(OUTPUT.read_text(encoding="utf-8"))
        if committed != generated:
            raise AssertionError("committed E13 identification certificate differs from regeneration")
    print(f"T73_E13_IDENTIFICATION={generated['verdict']}")
    print(f"E13={generated['E13_status']}")
    print(f"IDENTIFIED_WITH_SIGMA={generated['checks']['identified_with_Sigma_A_0']}")
    print(f"CS_OBJECT={generated['checks']['cs_object_computed']}")
    print(f"MISSING_MAPS={generated['checks']['missing_map_count']}")
    print(f"CERTIFICATE_SHA256={generated['certificate_sha256']}")


if __name__ == "__main__":
    main()
